### ISSUE TITLE
405 Method not allowed on Invoice.create

### ISSUE THREAD

**Issue by sento93** [chartmogul/chartmogul-python#17]
When I try to create an Invoice I get this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 65, in try_catch
    return (handler(*args, **kwargs), None)
  File "/usr/local/lib/python3.6/site-packages/chartmogul/resource.py", line 85, in _load
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.chartmogul.com/v1/import/customers/invoices

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/Users/sento/dev/test/chartmogul.py", line 66, in create_invoice
    return chartmogul.Invoice.create(config, uuid=cus_uuid, data=data).get().uuid
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 423, in get
    return self._target_settled_value(_raise=True)
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 426, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 187, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 65, in try_catch
    return (handler(*args, **kwargs), None)
  File "/usr/local/lib/python3.6/site-packages/chartmogul/errors.py", line 19, in annotateHTTPError
    raise_from(APIError(err.response.content), err)
  File "/usr/local/lib/python3.6/site-packages/future/utils/__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
chartmogul.errors.APIError: b'""'
```

**Comment by pkopac** [comment]
Hello @sento93!

First, let me apologize for the delay. From the call stack I see you're calling it as:
`chartmogul.Invoice.create(config, uuid=cus_uuid, data=data).get().uuid`
which looks fine. But the error suggests that `cus_uuid` is `None`. Can you please double-check that?
I've used [our unit test](https://github.com/chartmogul/chartmogul-python/blob/master/test/api/test_invoice.py#L263) `test_create` to verify this could be the case:
```
requests_mock.exceptions.NoMockAddress: No mock address: POST https://api.chartmogul.com/v1/import/customers/invoices
```

**Comment by pkopac** [comment]
I'll assume it's not a problem anymore, since there's no answer, so we can close this.
