### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'status' under v1.2.0

### ISSUE THREAD

**Issue by bparmind** [chartmogul/chartmogul-python#24]
Getting below error for  chartmogul.Ping.ping(config).get()

`pip install chartmogul==1.2.0`

```
Traceback (most recent call last):
  File "chartmogul_util.py", line 11, in <module>
    chartmogul.Ping.ping(config).get()
  File "/Library/Python/2.7/site-packages/promise/promise.py", line 510, in get
    return self._target_settled_value(_raise=True)
  File "/Library/Python/2.7/site-packages/promise/promise.py", line 514, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/Library/Python/2.7/site-packages/promise/promise.py", line 224, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/Library/Python/2.7/site-packages/promise/promise.py", line 85, in try_catch
    return (handler(*args, **kwargs), None)
  File "/Library/Python/2.7/site-packages/chartmogul/errors.py", line 21, in annotateHTTPError
    raise err
TypeError: __init__() got an unexpected keyword argument 'status'

```

**Comment by bparmind** [comment]
Seems like OS issue. closing for now.
